### ISSUE TITLE
no such file to load sqlite3

### ISSUE THREAD

**Issue by grosser** [LRDesign/logical-insight#10]
Is it sqlite3 only or is something wrong here ?

Exiting
/usr/local/rvm/gems/ruby-1.9.3-rc1/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:240:in `require': cannot load such file -- sqlite3 (LoadError)
    from /usr/local/rvm/gems/ruby-1.9.3-rc1/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:240:in`block in require'
    from /usr/local/rvm/gems/ruby-1.9.3-rc1/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /usr/local/rvm/gems/

**Comment by IdahoEv** [comment]
rack-bug (both ours and the Rails 2 original from brynary) uses sqlite3 to internally store debugging info (trace history, speed, etc.).  This is separate from your site database, so it won't change your app's mysql or postgres DB.   

However, it does mean you'll need to have the sqlite3 gem installed in order for rack-bug's internal functions to work.   Install the gem and your problem should go away.
